project:
  type: website
  output-dir: docs

website:
  title: "STA 1132 Descriptive Statistics"
  site-url: "https://thiyangt.github.io/descriptivestatisticsweb/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd



format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

