---
title: "Group Assignment"
---

Date released: July 15, 2025

As part of your coursework, you will be working on a group assignment. This assignment will contribute 10% towards your final grade. Below are the details:

**1. Group Formation:**

-   Please form groups consisting of 7 to 10 members.

-   **Group Leader:** Select someone to lead your group and keep things organized.

-   **Secretary:** Another member should be designated as the secretary, tasked with maintaining detailed meeting minutes to track our discussions and decisions.

-   Further assign the following roles:

    -   Deputy leader (If the group size is less than 8, no need to have a deputy leader.)

    -   Assistant secretary

    -   Research Coordinator - Data collection

    -   Research Coordinator - Introduction and Literature review
    
    -   Research Coordinator - Data analysis
    
    -   Research Coordinator - Report finalizing
    
    If there are more members, designate one or more as Research Coordinators and assign them specific task areas to oversee.
    
    All members should support each task. This task allocation is intended to coordinate the work."

**2. Assignment Task**

The aim of this assignment is to develop your data analysis and presentation skills by selecting and analyzing a publicly available data set. You need to prepare a report including the results of the analysis.

**Steps to Complete the Assignment:**

**1. Select a Publicly Available Data Set:**

-   Choose a data set from a reputable source such as the Central Bank of Sri Lanka, Department of Census and Statistics, or any other publicly available data set.

-   Ensure the data set is relevant to a topic of your interest and has sufficient data points for analysis.

-   If you find a very large data set, select a subset of the data. As you are going to do the calculations manually, it will be difficult to handle a large data set. It is recommended not to select data sets with more than 100 rows.

**2. Analyze Your Data Set:**

-   Conduct a thorough analysis of the data set using charts and tables.

-   Hand-Drawn Elements:

All charts, tables, and interpretations must be hand-drawn. Ensure they are clear, well-labeled, and accurately represent your findings.


**3. Submission Format:**

Submit the completed report as a single document following the specified format guidelines.

-   Cover page (Include group number)

-   Group members/ Index numbers/ Role/ Page contributed

-   Content:

    Title

    Content: Introduction, Objectives of the study,
     Data description, Data analysis, conclusions

    References

    Page number

-   Annexture

    -   Project timeline

    -   Meeting minutes

    -   Duties performed by the members (Assist the secretary in maintaining records and documentation, Ensure proper formatting and organization of the document, etc.)
    
    - Each members contribution to the report content
    
    
**Help guideline for the content**


**Introduction:**

Provide an overview of the topic and the importance of the data set.

**Objectives of the Study:**

Clearly state the goals and objectives of your analysis.

**Data:**

Describe the data set, including its source, type of data, and any preprocessing steps taken. (for example if you select a subset, you can mention it here)

**Data Analysis:**

Present your findings using **hand-drawn** charts and tables. Each visual and table should be accompanied by a brief interpretation.

**Conclusions:**

Summarize the key insights and implications of your analysis.


**4. Submission deadline**

August 5, 2025

The entire report should be hand written.

**You have been given a three-week timeframe to complete the assignment. Please begin work promptly to accommodate any unforeseen circumstances.**

This assignment provides an opportunity to deepen your understanding of statistical concepts and their practical applications while fostering teamwork and collaboration.

Every member should be familiar with the entire content of the report to ensure a comprehensive understanding

If you have any questions or require further clarification, please feel free to reach out to me (email: ttalagala\@sjp.ac.lk).

## Help desk

First help desk session will be held on July 16, 2025 from 3.15pm to 4.00pm.

If you need any additional support, please send an email to statdemos\@sci.sjp.ac.lk and reserve a time for a meeting (weekdays only between 8 a.m. and 4 p.m.).
